---
# tasks file for hudecof.gitlab

- name: "common | set os specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-{{ ansible_os_family }}.yml"
  tags:
    - gitlab
    - gitlab:package
    - gitlab:repository
    - gitlab:install
    - gitlab:config

- name: include package tasks
  include: packages-{{ ansible_os_family }}.yml
  tags:
    - gitlab
    - gitlab:package

- name: include repository tasks
  include: repository-{{ ansible_os_family }}.yml
  tags:
    - gitlab
    - gitlab:repository

- name: include install tasks
  include: install-{{ ansible_os_family }}.yml
  tags:
    - gitlab
    - gitlab:install

- name: include config tasks
  include: config-common.yml
  tags:
    - gitlab
    - gitlab:config
