---
- name: install repository key (redhat)
  rpm_key:
    key: "{{ key }}"
    state: present
  with_items: "{{ gitlab_gpg }}"
  loop_control:
    loop_var: key

- name: install repository (redhat)
  template:
    src: repository-RedHat.j2
    dest: /etc/yum.repos.d/gitlab_gitlab-ce.repo
    owner: root
    group: root
    mode: 0644
