---

- name: install repository key
  rpm_key:
    key: "{{ gitlab_gpg }}"
    state: present

- name: install repository (redhat)
  template:
    src: repository-RedHat.j2
    dest: /etc/yum.repos.d/gitlab_gitlab-ce.repo
    owner: root
    group: root
    mode: 0644
