---

- name: install repository key
  apt_key:
    url: "{{ gitlab_gpg }}"
    state: present
    keyring: /etc/apt/trusted.gpg.d/gitlab.gpg

- name: install repository (debian)
  template:
    src: repository-Debian.j2
    dest: /etc/apt/sources.list.d/gitlab_gitlab-ce.list
    owner: root
    group: root
    mode: 0644
  register: repository

- name: "repository update"
  apt:
    update_cache: yes
    cache_valid_time: 0
  when: repository|changed
